# This is a basic workflow that is manually triggered

name: Manual workflow
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  uploader:
    runs-on: ubuntu-latest
  
    steps:
      - name: createstuff
        run: echo "Hello World" 
      - uses: actions/checkout@v2.6.0
        with:
          # Repository name with owner. For example, actions/checkout
          repository: # optional, default is ${{ github.repository }}
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: example.png # or path/to/artifact    
    
